### ISSUE TITLE
Consider abstracting paths from deployment.yml

### ISSUE THREAD

**Issue by rhmk** [mk-ansible-roles/saphana-deploy#1]
<a href="https://github.com/kyleabenson"><img src="https://avatars0.githubusercontent.com/u/3821464?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kyleabenson](https://github.com/kyleabenson)**
_Sunday Feb 11, 2018 at 07:50 GMT_
_Originally opened as https://github.com/rhmk/ansible-hana-sysprep/issues/30_

----

Currently there is a lot of hardcoding of paths in deployment > tasks > deployment.yml, for example:

```
- name: create usr sap directory
  file:
    path: "/usr/sap/{{ item.value.hana_sid|upper }}"
    state: directory
  with_dict: "{{ instances }}"
```
I count that path 3 times in that file, so we could do something like:

```
var: 
  sap_usr_path: /usr/sap/{{ item.value.hana_sid|upper }}
```

This would improve legibility and reduce the number of manual paths, so it becomes easier to modify in the future if necessary. This is generally a good practice from a role reuse perspective.
